// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Copy_Copy,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu50-fsvh2104-2-e,HLS_INPUT_CLOCK=3.330000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.671450,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=847,HLS_SYN_LUT=1716,HLS_VERSION=2022_2}" *)

module Copy (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mem_read_addr_s_din,
        mem_read_addr_s_full_n,
        mem_read_addr_s_write,
        mem_read_addr_offset,
        mem_read_data_s_dout,
        mem_read_data_s_empty_n,
        mem_read_data_s_read,
        mem_read_data_peek_dout,
        mem_read_data_peek_empty_n,
        mem_read_data_peek_read,
        mem_write_addr_s_din,
        mem_write_addr_s_full_n,
        mem_write_addr_s_write,
        mem_write_addr_offset,
        mem_write_data_din,
        mem_write_data_full_n,
        mem_write_data_write,
        mem_write_resp_s_dout,
        mem_write_resp_s_empty_n,
        mem_write_resp_s_read,
        mem_write_resp_peek_dout,
        mem_write_resp_peek_empty_n,
        mem_write_resp_peek_read,
        n,
        flags
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [63:0] mem_read_addr_s_din;
input   mem_read_addr_s_full_n;
output   mem_read_addr_s_write;
input  [63:0] mem_read_addr_offset;
input  [512:0] mem_read_data_s_dout;
input   mem_read_data_s_empty_n;
output   mem_read_data_s_read;
input  [512:0] mem_read_data_peek_dout;
input   mem_read_data_peek_empty_n;
output   mem_read_data_peek_read;
output  [63:0] mem_write_addr_s_din;
input   mem_write_addr_s_full_n;
output   mem_write_addr_s_write;
input  [63:0] mem_write_addr_offset;
output  [512:0] mem_write_data_din;
input   mem_write_data_full_n;
output   mem_write_data_write;
input  [8:0] mem_write_resp_s_dout;
input   mem_write_resp_s_empty_n;
output   mem_write_resp_s_read;
input  [8:0] mem_write_resp_peek_dout;
input   mem_write_resp_peek_empty_n;
output   mem_write_resp_peek_read;
input  [63:0] n;
input  [63:0] flags;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg mem_read_addr_s_write;
reg mem_read_data_s_read;
reg mem_write_addr_s_write;
reg mem_write_data_write;
reg mem_write_resp_s_read;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] random_fu_274_p1;
reg   [0:0] random_reg_916;
reg   [0:0] read_reg_921;
reg   [0:0] write_reg_927;
wire   [0:0] icmp_ln79_fu_304_p2;
reg   [0:0] icmp_ln79_reg_933;
wire   [15:0] mask_18_fu_510_p3;
reg   [15:0] mask_18_reg_937;
wire   [0:0] icmp_ln85_6_fu_528_p2;
reg   [0:0] icmp_ln85_6_reg_942;
reg   [14:0] mask_19_reg_947;
wire   [0:0] icmp_ln85_7_fu_554_p2;
reg   [0:0] icmp_ln85_7_reg_952;
wire   [0:0] icmp_ln85_8_fu_570_p2;
reg   [0:0] icmp_ln85_8_reg_957;
wire   [0:0] icmp_ln85_9_fu_586_p2;
reg   [0:0] icmp_ln85_9_reg_962;
wire   [0:0] icmp_ln85_10_fu_602_p2;
reg   [0:0] icmp_ln85_10_reg_967;
wire   [15:0] mask_34_fu_878_p3;
reg   [15:0] mask_34_reg_982;
wire    ap_CS_fsm_state2;
wire   [0:0] tobool15_not_fu_887_p2;
reg   [0:0] tobool15_not_reg_987;
wire   [0:0] tobool17_not_fu_893_p2;
reg   [0:0] tobool17_not_reg_992;
wire   [0:0] or_ln116_fu_899_p2;
reg   [0:0] or_ln116_reg_997;
wire    grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_start;
wire    grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_done;
wire    grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_idle;
wire    grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_ready;
wire   [63:0] grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_addr_s_din;
wire    grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_addr_s_write;
wire   [512:0] grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_data_din;
wire    grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_data_write;
wire    grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_read_data_s_read;
wire   [63:0] grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_read_addr_s_din;
wire    grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_read_addr_s_write;
wire    grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_resp_s_read;
reg    grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [1:0] tmp_fu_294_p4;
wire   [47:0] tmp_21_fu_310_p4;
wire   [0:0] icmp_ln85_fu_320_p2;
wire   [48:0] tmp_22_fu_334_p4;
wire   [0:0] icmp_ln85_1_fu_344_p2;
wire   [15:0] select_ln85_fu_350_p3;
wire   [15:0] mask_fu_326_p3;
wire   [49:0] tmp_23_fu_366_p4;
wire   [15:0] mask_1_fu_358_p3;
wire   [14:0] mask_2_fu_382_p4;
wire   [0:0] icmp_ln85_2_fu_376_p2;
wire   [15:0] zext_ln86_fu_392_p1;
wire   [50:0] tmp_24_fu_404_p4;
wire   [15:0] mask_15_fu_396_p3;
wire   [14:0] mask_4_fu_420_p4;
wire   [0:0] icmp_ln85_3_fu_414_p2;
wire   [15:0] zext_ln86_1_fu_430_p1;
wire   [51:0] tmp_25_fu_442_p4;
wire   [15:0] mask_16_fu_434_p3;
wire   [14:0] mask_6_fu_458_p4;
wire   [0:0] icmp_ln85_4_fu_452_p2;
wire   [15:0] zext_ln86_2_fu_468_p1;
wire   [52:0] tmp_26_fu_480_p4;
wire   [15:0] mask_17_fu_472_p3;
wire   [14:0] mask_8_fu_496_p4;
wire   [0:0] icmp_ln85_5_fu_490_p2;
wire   [15:0] zext_ln86_3_fu_506_p1;
wire   [53:0] tmp_27_fu_518_p4;
wire   [54:0] tmp_28_fu_544_p4;
wire   [55:0] tmp_29_fu_560_p4;
wire   [56:0] tmp_30_fu_576_p4;
wire   [57:0] tmp_31_fu_592_p4;
wire   [15:0] zext_ln86_4_fu_608_p1;
wire   [15:0] mask_20_fu_611_p3;
wire   [14:0] mask_3_fu_617_p4;
wire   [15:0] zext_ln86_5_fu_627_p1;
wire   [15:0] mask_21_fu_631_p3;
wire   [14:0] mask_5_fu_638_p4;
wire   [15:0] zext_ln86_6_fu_648_p1;
wire   [15:0] mask_22_fu_652_p3;
wire   [14:0] mask_7_fu_659_p4;
wire   [15:0] zext_ln86_7_fu_669_p1;
wire   [15:0] mask_23_fu_673_p3;
wire   [14:0] mask_9_fu_680_p4;
wire   [15:0] zext_ln86_8_fu_690_p1;
wire   [58:0] tmp_32_fu_701_p4;
wire   [15:0] mask_24_fu_694_p3;
wire   [14:0] mask_25_fu_716_p4;
wire   [0:0] icmp_ln85_11_fu_710_p2;
wire   [15:0] zext_ln86_9_fu_726_p1;
wire   [59:0] tmp_33_fu_738_p4;
wire   [15:0] mask_26_fu_730_p3;
wire   [14:0] mask_27_fu_753_p4;
wire   [0:0] icmp_ln85_12_fu_747_p2;
wire   [15:0] zext_ln86_10_fu_763_p1;
wire   [60:0] tmp_34_fu_775_p4;
wire   [15:0] mask_28_fu_767_p3;
wire   [14:0] mask_29_fu_790_p4;
wire   [0:0] icmp_ln85_13_fu_784_p2;
wire   [15:0] zext_ln86_11_fu_800_p1;
wire   [61:0] tmp_35_fu_812_p4;
wire   [15:0] mask_30_fu_804_p3;
wire   [14:0] mask_31_fu_827_p4;
wire   [0:0] icmp_ln85_14_fu_821_p2;
wire   [15:0] zext_ln86_12_fu_837_p1;
wire   [62:0] tmp_36_fu_849_p4;
wire   [15:0] mask_32_fu_841_p3;
wire   [14:0] mask_33_fu_864_p4;
wire   [0:0] icmp_ln85_15_fu_858_p2;
wire   [15:0] zext_ln86_13_fu_874_p1;
reg    ap_block_state3_on_subcall_done;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_start_reg = 1'b0;
end

Copy_Copy_Pipeline_VITIS_LOOP_93_2 grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_start),
    .ap_done(grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_done),
    .ap_idle(grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_idle),
    .ap_ready(grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_ready),
    .mem_write_addr_s_din(grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_addr_s_din),
    .mem_write_addr_s_full_n(mem_write_addr_s_full_n),
    .mem_write_addr_s_write(grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_addr_s_write),
    .mem_write_data_din(grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_data_din),
    .mem_write_data_full_n(mem_write_data_full_n),
    .mem_write_data_write(grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_data_write),
    .n(n),
    .write_r(write_reg_927),
    .tobool15_not(tobool15_not_reg_987),
    .or_ln116_1(or_ln116_reg_997),
    .tobool17_not(tobool17_not_reg_992),
    .read_r(read_reg_921),
    .mask_57(mask_34_reg_982),
    .random(random_reg_916),
    .mem_read_data_s_dout(mem_read_data_s_dout),
    .mem_read_data_s_empty_n(mem_read_data_s_empty_n),
    .mem_read_data_s_read(grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_read_data_s_read),
    .mem_read_addr_offset_load(mem_read_addr_offset),
    .mem_read_addr_s_din(grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_read_addr_s_din),
    .mem_read_addr_s_full_n(mem_read_addr_s_full_n),
    .mem_read_addr_s_write(grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_read_addr_s_write),
    .mem_write_addr_offset_load(mem_write_addr_offset),
    .mem_write_resp_s_dout(mem_write_resp_s_dout),
    .mem_write_resp_s_empty_n(mem_write_resp_s_empty_n),
    .mem_write_resp_s_read(grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_resp_s_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_start_reg <= 1'b1;
        end else if ((grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_ready == 1'b1)) begin
            grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln79_reg_933 <= icmp_ln79_fu_304_p2;
        random_reg_916 <= random_fu_274_p1;
        read_reg_921 <= flags[32'd1];
        write_reg_927 <= flags[32'd2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln79_fu_304_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln85_10_reg_967 <= icmp_ln85_10_fu_602_p2;
        icmp_ln85_6_reg_942 <= icmp_ln85_6_fu_528_p2;
        icmp_ln85_7_reg_952 <= icmp_ln85_7_fu_554_p2;
        icmp_ln85_8_reg_957 <= icmp_ln85_8_fu_570_p2;
        icmp_ln85_9_reg_962 <= icmp_ln85_9_fu_586_p2;
        mask_18_reg_937[15 : 10] <= mask_18_fu_510_p3[15 : 10];
        mask_19_reg_947 <= {{mask_18_fu_510_p3[15:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mask_34_reg_982 <= mask_34_fu_878_p3;
        or_ln116_reg_997 <= or_ln116_fu_899_p2;
        tobool15_not_reg_987 <= tobool15_not_fu_887_p2;
        tobool17_not_reg_992 <= tobool17_not_fu_893_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_reg_933 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        mem_read_addr_s_write = grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_read_addr_s_write;
    end else begin
        mem_read_addr_s_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_reg_933 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        mem_read_data_s_read = grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_read_data_s_read;
    end else begin
        mem_read_data_s_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_reg_933 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        mem_write_addr_s_write = grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_addr_s_write;
    end else begin
        mem_write_addr_s_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_reg_933 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        mem_write_data_write = grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_data_write;
    end else begin
        mem_write_data_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_reg_933 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        mem_write_resp_s_read = grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_resp_s_read;
    end else begin
        mem_write_resp_s_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln79_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((icmp_ln79_fu_304_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state3_on_subcall_done = ((icmp_ln79_reg_933 == 1'd0) & (grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_start = grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_ap_start_reg;

assign icmp_ln79_fu_304_p2 = ((tmp_fu_294_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_10_fu_602_p2 = ((tmp_31_fu_592_p4 == 58'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_11_fu_710_p2 = ((tmp_32_fu_701_p4 == 59'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_12_fu_747_p2 = ((tmp_33_fu_738_p4 == 60'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_13_fu_784_p2 = ((tmp_34_fu_775_p4 == 61'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_14_fu_821_p2 = ((tmp_35_fu_812_p4 == 62'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_15_fu_858_p2 = ((tmp_36_fu_849_p4 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_1_fu_344_p2 = ((tmp_22_fu_334_p4 == 49'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_2_fu_376_p2 = ((tmp_23_fu_366_p4 == 50'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_3_fu_414_p2 = ((tmp_24_fu_404_p4 == 51'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_4_fu_452_p2 = ((tmp_25_fu_442_p4 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_5_fu_490_p2 = ((tmp_26_fu_480_p4 == 53'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_6_fu_528_p2 = ((tmp_27_fu_518_p4 == 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_7_fu_554_p2 = ((tmp_28_fu_544_p4 == 55'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_8_fu_570_p2 = ((tmp_29_fu_560_p4 == 56'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_9_fu_586_p2 = ((tmp_30_fu_576_p4 == 57'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_320_p2 = ((tmp_21_fu_310_p4 == 48'd0) ? 1'b1 : 1'b0);

assign mask_15_fu_396_p3 = ((icmp_ln85_2_fu_376_p2[0:0] == 1'b1) ? zext_ln86_fu_392_p1 : mask_1_fu_358_p3);

assign mask_16_fu_434_p3 = ((icmp_ln85_3_fu_414_p2[0:0] == 1'b1) ? zext_ln86_1_fu_430_p1 : mask_15_fu_396_p3);

assign mask_17_fu_472_p3 = ((icmp_ln85_4_fu_452_p2[0:0] == 1'b1) ? zext_ln86_2_fu_468_p1 : mask_16_fu_434_p3);

assign mask_18_fu_510_p3 = ((icmp_ln85_5_fu_490_p2[0:0] == 1'b1) ? zext_ln86_3_fu_506_p1 : mask_17_fu_472_p3);

assign mask_1_fu_358_p3 = ((icmp_ln85_1_fu_344_p2[0:0] == 1'b1) ? select_ln85_fu_350_p3 : mask_fu_326_p3);

assign mask_20_fu_611_p3 = ((icmp_ln85_6_reg_942[0:0] == 1'b1) ? zext_ln86_4_fu_608_p1 : mask_18_reg_937);

assign mask_21_fu_631_p3 = ((icmp_ln85_7_reg_952[0:0] == 1'b1) ? zext_ln86_5_fu_627_p1 : mask_20_fu_611_p3);

assign mask_22_fu_652_p3 = ((icmp_ln85_8_reg_957[0:0] == 1'b1) ? zext_ln86_6_fu_648_p1 : mask_21_fu_631_p3);

assign mask_23_fu_673_p3 = ((icmp_ln85_9_reg_962[0:0] == 1'b1) ? zext_ln86_7_fu_669_p1 : mask_22_fu_652_p3);

assign mask_24_fu_694_p3 = ((icmp_ln85_10_reg_967[0:0] == 1'b1) ? zext_ln86_8_fu_690_p1 : mask_23_fu_673_p3);

assign mask_25_fu_716_p4 = {{mask_24_fu_694_p3[15:1]}};

assign mask_26_fu_730_p3 = ((icmp_ln85_11_fu_710_p2[0:0] == 1'b1) ? zext_ln86_9_fu_726_p1 : mask_24_fu_694_p3);

assign mask_27_fu_753_p4 = {{mask_26_fu_730_p3[15:1]}};

assign mask_28_fu_767_p3 = ((icmp_ln85_12_fu_747_p2[0:0] == 1'b1) ? zext_ln86_10_fu_763_p1 : mask_26_fu_730_p3);

assign mask_29_fu_790_p4 = {{mask_28_fu_767_p3[15:1]}};

assign mask_2_fu_382_p4 = {{mask_1_fu_358_p3[15:1]}};

assign mask_30_fu_804_p3 = ((icmp_ln85_13_fu_784_p2[0:0] == 1'b1) ? zext_ln86_11_fu_800_p1 : mask_28_fu_767_p3);

assign mask_31_fu_827_p4 = {{mask_30_fu_804_p3[15:1]}};

assign mask_32_fu_841_p3 = ((icmp_ln85_14_fu_821_p2[0:0] == 1'b1) ? zext_ln86_12_fu_837_p1 : mask_30_fu_804_p3);

assign mask_33_fu_864_p4 = {{mask_32_fu_841_p3[15:1]}};

assign mask_34_fu_878_p3 = ((icmp_ln85_15_fu_858_p2[0:0] == 1'b1) ? zext_ln86_13_fu_874_p1 : mask_32_fu_841_p3);

assign mask_3_fu_617_p4 = {{mask_20_fu_611_p3[15:1]}};

assign mask_4_fu_420_p4 = {{mask_15_fu_396_p3[15:1]}};

assign mask_5_fu_638_p4 = {{mask_21_fu_631_p3[15:1]}};

assign mask_6_fu_458_p4 = {{mask_16_fu_434_p3[15:1]}};

assign mask_7_fu_659_p4 = {{mask_22_fu_652_p3[15:1]}};

assign mask_8_fu_496_p4 = {{mask_17_fu_472_p3[15:1]}};

assign mask_9_fu_680_p4 = {{mask_23_fu_673_p3[15:1]}};

assign mask_fu_326_p3 = ((icmp_ln85_fu_320_p2[0:0] == 1'b1) ? 16'd32767 : 16'd65535);

assign mem_read_addr_s_din = grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_read_addr_s_din;

assign mem_read_data_peek_read = 1'b0;

assign mem_write_addr_s_din = grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_addr_s_din;

assign mem_write_data_din = grp_Copy_Pipeline_VITIS_LOOP_93_2_fu_250_mem_write_data_din;

assign mem_write_resp_peek_read = 1'b0;

assign or_ln116_fu_899_p2 = (tobool17_not_fu_893_p2 | tobool15_not_fu_887_p2);

assign random_fu_274_p1 = flags[0:0];

assign select_ln85_fu_350_p3 = ((icmp_ln85_fu_320_p2[0:0] == 1'b1) ? 16'd16383 : 16'd32767);

assign tmp_21_fu_310_p4 = {{n[63:16]}};

assign tmp_22_fu_334_p4 = {{n[63:15]}};

assign tmp_23_fu_366_p4 = {{n[63:14]}};

assign tmp_24_fu_404_p4 = {{n[63:13]}};

assign tmp_25_fu_442_p4 = {{n[63:12]}};

assign tmp_26_fu_480_p4 = {{n[63:11]}};

assign tmp_27_fu_518_p4 = {{n[63:10]}};

assign tmp_28_fu_544_p4 = {{n[63:9]}};

assign tmp_29_fu_560_p4 = {{n[63:8]}};

assign tmp_30_fu_576_p4 = {{n[63:7]}};

assign tmp_31_fu_592_p4 = {{n[63:6]}};

assign tmp_32_fu_701_p4 = {{n[63:5]}};

assign tmp_33_fu_738_p4 = {{n[63:4]}};

assign tmp_34_fu_775_p4 = {{n[63:3]}};

assign tmp_35_fu_812_p4 = {{n[63:2]}};

assign tmp_36_fu_849_p4 = {{n[63:1]}};

assign tmp_fu_294_p4 = {{flags[2:1]}};

assign tobool15_not_fu_887_p2 = (read_reg_921 ^ 1'd1);

assign tobool17_not_fu_893_p2 = (write_reg_927 ^ 1'd1);

assign zext_ln86_10_fu_763_p1 = mask_27_fu_753_p4;

assign zext_ln86_11_fu_800_p1 = mask_29_fu_790_p4;

assign zext_ln86_12_fu_837_p1 = mask_31_fu_827_p4;

assign zext_ln86_13_fu_874_p1 = mask_33_fu_864_p4;

assign zext_ln86_1_fu_430_p1 = mask_4_fu_420_p4;

assign zext_ln86_2_fu_468_p1 = mask_6_fu_458_p4;

assign zext_ln86_3_fu_506_p1 = mask_8_fu_496_p4;

assign zext_ln86_4_fu_608_p1 = mask_19_reg_947;

assign zext_ln86_5_fu_627_p1 = mask_3_fu_617_p4;

assign zext_ln86_6_fu_648_p1 = mask_5_fu_638_p4;

assign zext_ln86_7_fu_669_p1 = mask_7_fu_659_p4;

assign zext_ln86_8_fu_690_p1 = mask_9_fu_680_p4;

assign zext_ln86_9_fu_726_p1 = mask_25_fu_716_p4;

assign zext_ln86_fu_392_p1 = mask_2_fu_382_p4;

always @ (posedge ap_clk) begin
    mask_18_reg_937[9:0] <= 10'b1111111111;
end

endmodule //Copy
